### ISSUE TITLE
Table lookup constraint does not cause mock prover to fail

### ISSUE THREAD

**Issue by sraver** [privacy-scaling-explorations/chiquito#168] opened 2023-11-01 08:20 UTC
## Issue

When trying to constrain the Semaphore circuit, I noticed that some table lookup constraints were not being respected.

I looked at the traces of the circuits, and it doesn't make sense to me why the lookups are not making the prover to fail, since the expected values are actually not there, I believe.

## How to reproduce

I added an example that reproduces the issue, it can be found in a branch of my forked repo, [here](https://github.com/sraver/chiquito/tree/sandro/table-lookup)

There is a file in [examples/lookup_table.py](https://github.com/sraver/chiquito/blob/sandro/table-lookup/examples/lookup_table.py).

In the example I create two base `Circuit`'s, which are connected on a `SuperCircuit`.
On the test execution, it can be seen how no step instances actually ever had a pair of values of `[99, 99]`, yet the prover doesn't fail, regardless of `CircuitTwoStep` having a lookup constraint over those values.

Another option would be to simply remove the hardcoded values from the `CircuitTwoStep` `setup` function. Since the initial values on the `trace` of both circuits are different, it should fail too.

**Comment by qwang98** [comment] 2023-11-01 22:50
Thanks for experimenting with different things! Always the best to hear from user feedbacks and hopefully uncover bugs.

I briefly read through your linked example and my immediate reaction is that lookup table should be created with fixed signals, not forward, because forward signals assignments can change given different witnesses, while lookup tables should be consistent across all applications of them (here in your example, it's applied in Circuit2, but we might apply it else where as well).

`self.a` and `self.b` are forward signals here: https://github.com/sraver/chiquito/blob/sandro/table-lookup/examples/lookup_table.py#L37-L41

Maybe try this and see if the issue is fixed. I'd also note that fixed signals are assigned using the `fixed_gen` function. The assign function is also slightly different as you need one extra parameter for the offset, because the cell manager does the cell position assignment for `wg`, which is for a specific step instance, while the fixed signals are called "fixed" for a reason, i.e. you assign their positions! :) 

If the fix works after applying this change, we should have another PR that confines signals that go into a table to be "fixed" for both Python and Rust. @leolara Let me know if you agree. Feel free to work on this PR or I'm also happy to fix it.

**Comment by leolara** [comment] 2023-11-02 05:24
So, halo2 allows adivce lookup tables, so forwards should be also allowed. That is actually how the zkEVM sub circuits are connected

**Comment by sraver** [comment] 2023-11-02 06:26
ok, I'm going to dive a bit into the code see if I find why it's not constraining :pray:

**Comment by sraver** [comment] 2023-11-02 12:13
btw @qwang98 , thanks for looking into it! :heart: 

The problem I found with using `fixed_gen` is that I couldn't pass external data from the `mapping`, and I need to generate the tables based on data that will come from the witness.

**Comment by qwang98** [comment] 2023-11-02 14:10
Got it. I think according to Leo, we should be able to make lookup tables with witness based (not just fixed generation based) signals, so I'll look more into this example.

Thanks!

**Comment by qwang98** [comment] 2023-11-02 14:13
> btw @qwang98 , thanks for looking into it! ❤️
> 
> The problem I found with using `fixed_gen` is that I couldn't pass external data from the `mapping`, and I need to generate the tables based on data that will come from the witness. Is there any way to send data into it maybe?

By passing external data from mapping or sending external data to it, would the following work?

https://github.com/sraver/chiquito/blob/sandro/table-lookup/examples/mimc7.py#L162-L163

So the MiMC7 circuit takes in external input for the trace, so if you edit the trace of CircuitOne and pass in the data from this line https://github.com/sraver/chiquito/blob/sandro/table-lookup/examples/lookup_table.py#L113-L114 by passing in the input for mapping, which cascades to trace, and cascades to wg?

**Comment by qwang98** [comment] 2023-11-02 19:46
FYI I found the bug and am fixing it.

**Comment by qwang98** [comment] 2023-11-02 20:46
It's fixed. I'll submit a new PR.
<img width="1031" alt="Screen Shot 2023-11-02 at 16 46 38" src="https://github.com/privacy-scaling-explorations/chiquito/assets/117886596/283b0f24-1d8f-49b3-adbd-90afe7651f87">

**Comment by qwang98** [comment] 2023-11-02 20:48
Issue that happened here: 
1. Had a bug in Serde deserializer that failed to store the parsed Lookup in Rust AST.
2. Had another Python frontend bug that uses the single circuit compile function rather than the by phase compile functions for super circuits.

MiMC7 and this example have both been fixed. Thanks so much for spotting this! @sraver

**Comment by qwang98** [comment] 2023-11-02 21:09
FYI, the Python package update won't be applied till #173 is merged to main. If you'd like to test the example, would need to use the PR branch for now.

**Comment by sraver** [comment] 2023-11-03 00:41
@qwang98 you da man! :fire: :firefighter: Reading the fix rn :blush: 

BTW, you think it makes sense to have te `lookup_table.py` example in the repo? Otherwise I'll just remove the branch.

**Closed** 2023-11-03 01:42 UTC
Labels: bug
